version: '3'
services:
  api:
    build: ./back
    container_name: sanic
    restart: always
    ports:
      - 8000:8000

  database:
    image: postgres:10
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=bovespaapp
      - POSTGRES_PASSWORD=bovespaapp
      - POSTGRES_DB=bovespaapp
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
